#!/usr/bin/env bash
# Regenerate data/demographic_models/*.tsv from the compiled simulator.
#
# The Ne[]/T[] arrays are defined in src/simulations/single_site_simulator.cpp;
# these .tsv files are a dump of them. --dump-demography steps through the whole
# history one generation at a time through the real popsize() and checks that
# every epoch is entered exactly once, so it exits non-zero on a bad table.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="$REPO/src/simulations/bin/single_site_simulator"
OUT="$REPO/data/demographic_models"

[ -x "$BIN" ] || { echo "build the simulators first: make sims" >&2; exit 1; }
mkdir -p "$OUT"

emit() {   # $1 = pop key, $2 = output stem, $3 = label, $4 = recent source, $5 = switch gen
  local f="$OUT/$2.tsv"
  {
    echo "# $3 demographic history, as compiled into the simulators."
    echo "# Generated by: src/simulations/bin/single_site_simulator --dump-demography $1"
    echo "# Do not edit by hand -- regenerate with 'make models' from the repo root."
    echo "#"
    echo "# Ancient portion : Schiffels & Durbin (2014), MSMC"
    echo "# Recent portion  : $4, from generation $5 to the present"
    echo "#"
    echo "# Tabulated in generations before the present. Epoch i has size Ne and spans"
    echo "# gen_hi >= gen >= gen_lo, i.e. the closed interval [gen_lo, gen_hi]."
    echo "# Epoch 0 is ancestral: it applies to every generation older than T[0]."
    echo "# The simulations themselves run forward in time, from the oldest epoch to"
    echo "# the present."
    echo "#"
    "$BIN" --dump-demography "$1" 2>&1 | sed -n '1,2p' | sed 's/^/# /; s/^# #/#/'
    printf 'epoch\tgen_hi\tgen_lo\tNe\n'
    "$BIN" --dump-demography "$1" 2>&1 \
      | awk -F'\t' 'NF==6 && $1!="epoch" {print $1"\t"$2"\t"$3"\t"$4}'
  } > "$f"
  echo "wrote $f ($(grep -vc '^#' "$f") rows)"
}

emit eur NFE_schiffels_durbin_schraiber "non-Finnish European (NFE)"        "Schraiber et al. (2025)" 517
emit sas SAS_schiffels_durbin_kar       "South Asian (SAS)"                 "Kar et al. (2026)"      1054
emit afr AFR_schiffels_durbin_kar       "African / African-American (AFR)"  "Kar et al. (2026)"      1200
